import type { AppNode } from "@/types/flow"

function safeId(nodeId: string): string {
  return nodeId.replace(/[^a-zA-Z0-9]/g, "_")
}

function pyDict(h: Record<string, string>): string {
  const e = Object.entries(h)
  if (e.length === 0) return "{}"
  return `{${e.map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(", ")}}`
}

function oneStep(node: AppNode): string {
  const sid = safeId(node.id)
  const m = node.data.method.toUpperCase()
  const url = node.data.url
  const headers = pyDict(node.data.headers ?? {})
  const hasBody =
    Boolean(node.data.body?.trim()) &&
    m !== "GET" &&
    m !== "HEAD" &&
    m !== "CONNECT" &&
    m !== "TRACE"

  const bodyLine = hasBody
    ? `_content = ${JSON.stringify(node.data.body!)}.encode("utf-8")`
    : "_content = None"

  const printLine =
    '    print(f"[' +
    node.id.slice(0, 8) +
    '] {_method} {_r.status_code} {_ms:.1f}ms")'

  return [
    `async def step_${sid}(client: httpx.AsyncClient) -> None:`,
    `    _method = ${JSON.stringify(m)}`,
    `    _url = ${JSON.stringify(url)}`,
    `    _headers = ${headers}`,
    `    ${bodyLine}`,
    `    _kw = {"method": _method, "url": _url, "headers": _headers}`,
    `    if _content is not None:`,
    `        _kw["content"] = _content`,
    `    _r = await client.request(**_kw)`,
    `    _ms = _r.elapsed.total_seconds() * 1000.0`,
    printLine,
  ].join("\n")
}

export function generatePythonScript(
  nodes: AppNode[],
  batches: string[][],
): string {
  const byId = new Map(nodes.map((n) => [n.id, n]))
  const header = `# Generated by FlowCheck (deterministic export, no AI).
# Requires: pip install httpx
# Same execution waves as the app: parallel within a batch, sequential batches.

import asyncio
import httpx

TIMEOUT_S = 60.0
`

  const funcs = nodes.map((n) => oneStep(n)).join("\n\n")

  const mainParts: string[] = []
  mainParts.push("\nasync def main() -> None:")
  mainParts.push(
    "    async with httpx.AsyncClient(timeout=TIMEOUT_S, follow_redirects=True) as client:",
  )

  batches.forEach((batch, i) => {
    const calls = batch
      .map((id) => `step_${safeId(id)}(client)`)
      .join(",\n            ")
    mainParts.push(`        # wave ${i + 1}`)
    mainParts.push(`        await asyncio.gather(`)
    mainParts.push(`            ${calls},`)
    mainParts.push(`        )`)
  })

  mainParts.push(`
if __name__ == "__main__":
    asyncio.run(main())
`)

  const missing = batches.flat().filter((id) => !byId.has(id))
  if (missing.length) {
    throw new Error("Internal: batch references unknown node")
  }

  return `${header}\n${funcs}\n${mainParts.join("\n")}\n`
}
