import type { AppNode } from "@/types/flow"

function safeId(nodeId: string): string {
  return nodeId.replace(/[^a-zA-Z0-9]/g, "_")
}

function oneStep(node: AppNode): string {
  if (node.type !== "http") {
    return `
async function step_${safeId(node.id)}() {
  console.log("[${node.id.slice(0, 8)}]", "(skipped in export — not an HTTP node)");
}
`.trimEnd()
  }
  const sid = safeId(node.id)
  const m = node.data.method.toUpperCase()
  const url = JSON.stringify(node.data.url)
  const headers = JSON.stringify(node.data.headers ?? {})
  const hasBody =
    Boolean(node.data.body?.trim()) &&
    m !== "GET" &&
    m !== "HEAD" &&
    m !== "CONNECT" &&
    m !== "TRACE"

  const optionsObj = hasBody
    ? `{ method, headers, body: ${JSON.stringify(node.data.body!)} }`
    : `{ method, headers }`

  return `
async function step_${sid}() {
  const method = ${JSON.stringify(m)};
  const url = ${url};
  const headers = ${headers};
  const options = ${optionsObj};
  const t0 = performance.now();
  const res = await fetch(url, options);
  const ms = performance.now() - t0;
  console.log("[${node.id.slice(0, 8)}]", method, res.status, ms.toFixed(1) + "ms");
}
`.trimEnd()
}

export function generateNodeScript(
  nodes: AppNode[],
  batches: string[][],
): string {
  const header = `// Generated by FlowCheck (deterministic export, no AI).
// Run with: node this-file.mjs  (Node 18+ for global fetch)

`

  const funcs = nodes.map((n) => oneStep(n)).join("\n\n")

  const waves = batches
    .map((batch, i) => {
      const calls = batch.map((id) => `step_${safeId(id)}()`).join(",\n    ")
      return `  // wave ${i + 1}\n  await Promise.all([\n    ${calls},\n  ]);`
    })
    .join("\n\n")

  const main = `
async function main() {
${waves}
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
`

  return `${header}${funcs}\n${main}`
}
